baseURL = "https://notation.co.jp/"
languageCode = "ja-jp"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false
title = "合同会社ノーテーション"
theme = "stack"
hasCJKLanguage = true
enableRobotsTXT = true

[languages]
  [languages.ja]
    languageName = "日本語"
    languageCode = "ja-jp"
    weight = 1
    title = "合同会社ノーテーション"
    contentDir = "content"

  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 2
    title = "Notation LLC"
    contentDir = "content/en"

[services]
  [services.googleAnalytics]
    ID = "G-7JHDWKH526"

[minify]
  disableXML = true
  minifyOutput = true

[permalinks]
  post = "/:slug/"
  page = "/:slug/"

[params]
  mainSections = ["post"]
  description = "データ可視化の研修・講演・執筆・教育を通じて、表現伝達と課題解決の交差点に新しい記法を提供します。合同会社ノーテーション代表・矢崎裕一の活動紹介サイト。"
  featuredImageField = "image"
  rssFullContent = true

[params.footer]
  since = 2026
  customText = ""

[params.dateFormat]
  published = "2006-01-02"
  lastUpdated = "2006-01-02 15:04 MST"

[params.sidebar]
  emoji = ""
  subtitle = "合同会社ノーテーション／矢崎裕一の活動紹介サイトです"
  description = "データ可視化は表現伝達と課題解決の交差点として、世の中に新しい記法を提供します。"

[params.sidebar.avatar]
  enabled = true
  local = true
  src = "img/logo.png"

[params.sidebar.author]
  name = "矢崎裕一"
  image = "img/logo.png"
  bio = "合同会社ノーテーション代表。データ可視化の実践、教育、普及活動に従事。株式会社ビジネス・アーキテクツにてユーザー・インターフェイス・デザイナーおよびアート・ディレクターを7年間経験後、独立。企業や教育機関での講義活動、ウェブサイトVisualizing.JPにおける情報発信、コミュニティData Visualization Japanにおけるコミュニティ活動など、データ可視化の実践と普及に関する活動をおこなっている。単著『データ可視化の基本が全部わかる本』、共著『RESASの教科書』(日経BP、2016)。千葉工業大学デザイン科学修士修了。データ・ビジュアライゼーション・ジャパン発起人/Yahoo!ニュース・エキスパート。"

[params.article]
  math = false
  toc = true
  readingTime = true

[params.article.license]
  enabled = false
  default = ""

[params.comments]
  enabled = false
  provider = ""

[params.widgets]
  homepage = [
      { type = "search" },
      { type = "archives", params = { limit = 5 } },
      { type = "categories", params = { limit = 10 } },
      { type = "tag-cloud", params = { limit = 10 } }
  ]

[[params.widgets.page]]
  type = "toc"

[params.opengraph.twitter]
  site = "@visualizing_jp"
  card = "summary"

[params.defaultImage.opengraph]
  enabled = true
  local = true
  src = "img/avatar.png"

[params.colorScheme]
  toggle = false
  default = "dark"

[params.imageProcessing.cover]
  enabled = true

[params.imageProcessing.content]
  enabled = true

[pagination]
  pagerSize = 15

[[languages.ja.menu.main]]
  identifier = "posts"
  name = "トップ"
  url = "/"
  weight = 10

[[languages.ja.menu.main]]
  identifier = "about"
  name = "矢崎裕一について"
  url = "/about/"
  weight = 20

[[languages.ja.menu.main]]
  identifier = "lecture"
  name = "研修"
  url = "/categories/lecture/"
  weight = 60

[[languages.ja.menu.main]]
  identifier = "talk"
  name = "講演"
  url = "/categories/talk/"
  weight = 65

[[languages.ja.menu.main]]
  identifier = "education"
  name = "教育"
  url = "/categories/education/"
  weight = 70

[[languages.ja.menu.main]]
  identifier = "journalism"
  name = "報道"
  url = "/categories/journalism/"
  weight = 80

[[languages.ja.menu.main]]
  identifier = "civictech"
  name = "シビックテック"
  url = "/categories/civictech/"
  weight = 90

[[languages.ja.menu.main]]
  identifier = "codefor"
  name = "Code for X"
  url = "/categories/codefor/"
  weight = 95

[[languages.ja.menu.main]]
  identifier = "inquiry"
  name = "お問い合わせ"
  url = "https://forms.gle/VoK2d2BCKyHQaD6y9"
  weight = 99

[[languages.ja.menu.main]]
  identifier = "english"
  name = "English"
  url = "/en/about/"
  weight = 100

[[languages.en.menu.main]]
  identifier = "about"
  name = "About"
  url = "/en/about/"
  weight = 10

[[languages.en.menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "mailto:info@notation.co.jp"
  weight = 20

[[languages.en.menu.main]]
  identifier = "japanese"
  name = "日本語"
  url = "/"
  weight = 30

[related]
  includeNewer = true
  threshold = 60
  toLower = false

[[related.indices]]
  name = "tags"
  weight = 100

[[related.indices]]
  name = "categories"
  weight = 200

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  endLevel = 4
  ordered = true
  startLevel = 2

[markup.highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  tabWidth = 4
